services:
  mcp-searxng:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SEARXNG_URL=http://searxng:8080
    depends_on:
      - searxng
    volumes:
      - ./src:/app/src

  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng_config:/etc/searxng:ro
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
      - INSTANCE_NAME="mcp-searxng-instance"
      - SEARXNG_VALKEY_URL=valkey://valkey:6379/0
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    depends_on:
      - valkey

  valkey:
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save "" --appendonly no


